name: himar
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - cccl=2.3.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cccl=12.4.127
  - cuda-cccl_win-64=12.4.127
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=12.4
  - filelock=3.13.1
  - freetype=2.12.1
  - gmpy2=2.1.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.22
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - pillow=10.4.0
  - pip=20.3.3
  - pysocks=1.7.1
  - python=3.8.5
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - accelerate==1.0.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - bleach==6.1.0
      - cachetools==5.5.2
      - clean-fid==0.1.35
      - cmake==4.0.3
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==3.1.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diffusers==0.32.2
      - dill==0.3.8
      - docopt==0.6.2
      - einops==0.8.1
      - evaluate==0.4.3
      - executing==2.2.1
      - fairscale==0.4.13
      - fastjsonschema==2.21.2
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - huggingface-hub==0.30.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmcv==1.7.0
      - mmengine==0.10.7
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ninja==1.11.1.4
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.4.0
      - pytz==2025.2
      - pywin32==311
      - pyzmq==27.1.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rpds-py==0.20.1
      - rsa==4.9
      - safetensors==0.5.3
      - scipy==1.10.1
      - six==1.17.0
      - soupsieve==2.7
      - stack-data==0.6.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - timm==1.0.17
      - tinycss2==1.2.1
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torchaudio==2.2.2
      - torchmetrics==1.5.2
      - torchvision==0.17.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - tzdata==2025.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - werkzeug==3.0.6
      - xformer==1.0.1
      - xformers==0.0.25
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarg==0.1.9
      - yarl==1.15.2
      - zipp==3.20.2
prefix: C:\miniconda3\envs\himar
